export const ADD_STORY = 'STORY_ACTION:ADD_STORY';
export const SEND_STORY = 'STORY_ACTION:SEND_STORY';
export const SEND_VOTING = 'VOTING_ACTION:SEND_VOTING';
export const CHANGE_ACTIVITY = 'CHANGE_ACTIVITY';
