export const ADD_POST = 'POST_ACTION:ADD_POST';
export const SEND_POST = 'POST_ACTION:SEND_POST';
export const DELETE_POST = 'POST_ACTION:DELETE_POST';
export const REACT_POST = 'POST_ACTION:REACT_POST';
export const CREATE_REACTION = 'CREATE_REACTION';
export const ADD_NEW_REACTION = 'ADD_NEW_REACTION';
