export const ADD_TO_WATCHLIST = 'WATCHLIST:ADD_TO_WATCHLIST';
export const REMOVE_FROM_WATCHLIST = 'WATCHLIST:REMOVE_FROM_WATCHLIST';
export const UPDATE_WATCHLIST_ITEM = 'WATCHLIST:UPDATE_WATCHLIST_ITEM';
